language: ruby
rvm:
 - 2.4.0
sudo: false
cache: bundler
before_script:
  - psql -c 'create database hpi_swt2_test;' -U postgres
script:
  - bundle exec rake db:test:prepare
  - xvfb-run bundle exec rspec spec/